[package]
name        = "terp-mint-hooks-derive"
version      = { workspace = true }
description = "Macros for generating code used by the `terp-mint-hooks` crate"
authors     = ["Shane Vitarana <s@users.noreply.publicawesome.com>"]
edition     = { workspace = true }
homepage    = { workspace = true }
repository  = { workspace = true }
license     = { workspace = true }

[lib]
doctest    = false # disable doc tests
proc-macro = true

[dependencies]
proc-macro2    = "1"
quote          = "1"
syn            = "1"
terp-code-controllers = { workspace = true }
