# coverage:
#   precision: 2
#   round: down
#   range: 90...100

#   status:
#     project:
#       default:
#         threshold: 6%
#         target: 90%
#     patch:
#       default:
#         enabled: no
# ignore:
#   - "packages/utils/terp-sdk/.*"
#   - "packages/utils/terp-multi-test/.*"
#   - "unit-tests"
