[package]
name        = "terp-mint-hooks"
authors     = ["Shane Vitarana <s@users.noreply.publicawesome.com>",
"A Hardnett <returniflost@skiff.com>"]
description = "Mint hooks to allow extending minting contracts"
version     = { workspace = true }
edition     = { workspace = true }
homepage    = { workspace = true }
repository  = { workspace = true }
license     = { workspace = true }

[dependencies]
cosmwasm-schema      = { workspace = true }
cosmwasm-std         = { workspace = true }
cw-storage-plus      = { workspace = true }
schemars             = { workspace = true }
serde                = { workspace = true }
terp-code-controllers       = { workspace = true }
terp-sdk               = { workspace = true }
thiserror            = { workspace = true }
terp-mint-hooks-derive = { path = "./derive", version = "0.1.0" }
